Repository UBC-MDS/picfixPy, pull requests merged in 2019-02, with the labels that each got.

#15 created vibrance function
  picfixPy/vibrance.py
Labels: help wanted

#20 Vibrance testing and funciton updates
  picfixPy/contrast.py
  picfixPy/test/img2.jpg
  picfixPy/test/test_img/vibrance/expected_img1.png
  picfixPy/test/test_img/vibrance/vibrance.png
  picfixPy/test/test_vibrance.py
  picfixPy/vibrance.py
Labels: feature

#24 Update readme
  README.md
  picfixPy/test/test_img/contrast_output.png
  picfixPy/test/test_img/sharpen_output.png
  picfixPy/test/test_img/vibrance_output.png
  setup.py
Labels: documentation

#27 Minor edits
  README.md
  picfixPy/contrast.py
  picfixPy/sharpen.py
  picfixPy/test/test_sharpen.py
  picfixPy/test/test_vibrance.py
  picfixPy/vibrance.py
  setup.py
Labels: documentation
